### ISSUE TITLE
특정 사용자에게 발생하는 자동 로그인 및 구문 에러 이슈

### ISSUE THREAD

**Issue by kimwonjuun** [kimwonjuun/no-sunday#68]
### 이슈 🚨
> **사이트 접속 시 특정 사용자에게만 자동 로그인과 마이페이지 접속 시 구문 에러(SyntaxError) 발생함.**

**1. 첫 번째 이슈 🔥**

![image](https://user-images.githubusercontent.com/117059038/226333901-008357aa-4b94-40ba-8a85-b3bc529c91e6.png)
- 사이트 접속 시 정상 출력 화면.

![image](https://user-images.githubusercontent.com/117059038/226333643-35cfa7ae-c807-4515-9327-557a3054817a.png)
- 사이트 접속 시 특정 사용자 자동 로그인된 화면.

**=> 해당 프로젝트는 로그인 정보를 세션 스토리지에 저장하고 있기 때문에 비로그인 상태로 접속이 되는 것이 정상임.**

**2. 두 번째 이슈 🔥**

![image](https://user-images.githubusercontent.com/117059038/226336452-291e20a2-7075-4d5b-8dc0-e2b9ffdc2f96.png)
- 정상 출력된 마이페이지.

![image](https://user-images.githubusercontent.com/117059038/226336794-579fe484-9cd5-485e-9494-fecb87b30a9f.png)
- 특정 사용자 마이페이지 접근 시 나타나는 구문 에러.

**=> 로그인 후 정상적으로 접근이 가능하던 마이페이지에 특정 사용자가 접근하면 해당 에러가 발생하며 렌더링이 되지 않음.**

![image](https://user-images.githubusercontent.com/117059038/226340464-5ea7ae92-9f49-46c0-983a-8e4f22ef0392.png)

**=> 해당 에러가 가리키는 코드. 특정 사용자(1명) 제외 사용자들은 해당 코드에서 아무 문제가 없었음.**
**=> 특정 사용자 또한 프로젝트 완성 후 최소 일주일 1회 이상 해당 사이트에 방문하며 이슈 없었으나 지난주(3. 13~ 3. 17) 사이 해당 이슈 발견함.**

**Comment by yujleee** [comment]
멋진 정리입니다! 👍

**Comment by kimwonjuun** [comment]
`  // const isLoggedIn = sessionStorage.key(0);
  const isLoggedIn = sessionStorage.getItem(
    `firebase:authUser:${firebaseConfig.apiKey}:[DEFAULT]`,
  );`

차후 혹시 모를 변수에 대비해 기존 헤더 컴포넌트에서 세션스토리지의 첫 번째 키로 로그인 유저를 확인하던 방식을 해당 에러처럼 특정 사용자가 크롬 익스텐션과의 이슈로 잘못된 키 값을 받아와 유저 확인이 불가능할 수 있으니 세션스토리지의 파이어베이스 키 값 만을 가져오게 수정함.

**Comment by kimwonjuun** [comment]
특정 사용자의 pc에 Live color picker 라는 크롬 익스텐션이 원인임을 발견함. 
![image](https://user-images.githubusercontent.com/117059038/226777487-64c8c943-a8f9-4e74-b4ee-f1817329877a.png)
이슈 발생 기간에 해당 익스텐션을 설치/삭제하거나 다루지 않아 당장 원인 파악은 불가. 비활성화 후 접속 시 코드 상 의도했던 정상적인 세션스토리지 키가 들어옴.

![image](https://user-images.githubusercontent.com/117059038/226777947-852265d4-ecae-4d77-b885-c30e79995e0d.png)
![image](https://user-images.githubusercontent.com/117059038/226778261-76a08070-d335-40c5-9472-97e2995cb132.png)
=> Live color picker 익스텐션이 활성화 된 상태로 사이트 접속 시 나타나는 비로그인 상태의 세션스토리지 키.

![image](https://user-images.githubusercontent.com/117059038/226778504-47d248dc-483e-4c7a-90ff-6dcc7b4ffab4.png)
=> Live color picker 익스텐션 비활성화 후 사이트 접속 시 정상적인 비로그인 상태의 세션 스토리지.

![image](https://user-images.githubusercontent.com/117059038/226778680-0083f812-e549-4ad3-835f-41317b99c570.png)
=> 로그인 후 정상적인 키.

**Comment by kimwonjuun** [comment]
// 기존 코드
// const isLoggedIn = sessionStorage.key(0);
// 변경 코드
const isLoggedIn = sessionStorage.getItem(firebase:authUser:${firebaseConfig.apiKey}:[DEFAULT], );

차후 혹시 모를 변수에 대비해 기존 헤더 컴포넌트에서 세션스토리지의 첫 번째 키로 로그인 유저를 확인하던 방식을 해당 에러처럼 특정 사용자가 크롬 익스텐션과의 이슈로 잘못된 키 값을 받아와 유저 확인이 불가능할 수 있으니 세션스토리지의 파이어베이스 키 값 만을 가져오게 수정함.
